DROP TABLE IF EXISTS images CASCADE;

CREATE TABLE images (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  img_url VARCHAR(255) NOT NULL,
  prompt_text VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);