DROP TABLE IF EXISTS favourite_images CASCADE;

CREATE TABLE favourite_images (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  image_id INTEGER REFERENCES images(id) ON DELETE CASCADE
);